server:
  port: 88
spring:
  cloud:
    gateway:
      routes:
        - id: qq_route
          uri: https://www.qq.com
          predicates:
            - Query=url, qq
        - id: baidu_route
          uri: https://www.baidu.com
          predicates:
            - Query=url, baidu

        - id: third_party_route
          uri: lb://shopee-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            # 在yml文档中 $ 要写成 $\
            - RewritePath=/api/thirdparty/(?<segment>/?.*),/$\{segment}

        - id: renren_fast_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            # 此工厂将/api/(?.*)重写为{segment}，然后转发到 lb://renren-fast
            - RewritePath=/api(?<segment>/?.*), /renren-fast$\{segment}

        - id: product_route
          uri: lb://shopee-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api(?<segment>/?.*), $\{segment}
    nacos:
      discovery:
        server-addr: localhost:8848
logging:
  level:
    io.github.xiaoyureed: debug