server:
  port: 88
spring:
  cloud:
    gateway:
      routes:
        - id: qq_route
          uri: https://www.qq.com
          predicates:
            - Query=url, qq
        - id: baidu_route
          uri: https://www.baidu.com
          predicates:
            - Query=url, baidu
